"use client";
import { useMemo,useState } from "react"; import type { Lesson } from "@/lib/types"; import { LessonNotes } from "@/components/lesson-notes";
export function LessonClient({lesson,courseTitle,nextHref}:{lesson:Lesson;courseTitle:string;nextHref?:string}){const [tab,setTab]=useState<'lesson'|'transcript'|'tutor'>('lesson');const [code,setCode]=useState(lesson.lab?.starterCode||'');const [labMsg,setLabMsg]=useState('');const [question,setQuestion]=useState('');const [answer,setAnswer]=useState('');const [asking,setAsking]=useState(false);const [speaking,setSpeaking]=useState(false);
 const preview=useMemo(()=>lesson.lab?.language==='html'?code:'',[code,lesson.lab?.language]);
 function speak(){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${lesson.title}. ${lesson.transcript} ${lesson.content}`);u.rate=.95;u.onend=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(u)}
 function checkLab(){const req=lesson.lab?.expectedContains||[];const missing=req.filter(x=>!code.toLowerCase().includes(x.toLowerCase()));setLabMsg(missing.length?`Keep going. Your work still needs: ${missing.join(', ')}.`:'Great work. Your solution includes the key requirements for this lab.');}
 async function ask(){if(!question.trim())return;setAsking(true);setAnswer('');const res=await fetch('/api/ai/tutor',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({courseId:lesson.courseId,lessonId:lesson.id,question})});const d=await res.json();setAsking(false);setAnswer(d.answer||d.error||'No answer was returned.');}
 async function complete(){await fetch('/api/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({courseId:lesson.courseId,lessonId:lesson.id,completed:true})});if(nextHref) location.href=nextHref;else location.href='/dashboard';}
 return <div className="lesson-main"><div className="lesson-top"><div><span className="eyebrow">{courseTitle}</span><h1>{lesson.title}</h1><p>{lesson.summary}</p></div><button className="btn btn-ghost" onClick={speak}>{speaking?'Speaking…':'🔊 AI narration'}</button></div><div className="lesson-tabs"><button className={tab==='lesson'?'active':''} onClick={()=>setTab('lesson')}>Lesson</button><button className={tab==='transcript'?'active':''} onClick={()=>setTab('transcript')}>Transcript</button><button className={tab==='tutor'?'active':''} onClick={()=>setTab('tutor')}>AI tutor</button></div>
 {tab==='lesson'&&<div className="lesson-content"><div className="reading-card"><LessonNotes text={lesson.content}/></div>{lesson.lab&&<div className="lab-card"><div className="lab-heading"><div><span className="eyebrow">Guided practical</span><h2>Try it yourself</h2></div><span className="pill dark">{lesson.lab.language}</span></div><ol>{lesson.lab.instructions.map((s,i)=><li key={i}>{s}</li>)}</ol><textarea className="code-editor" value={code} onChange={e=>setCode(e.target.value)} spellCheck={false}/>{preview&&<iframe className="preview-frame" title="Lab preview" srcDoc={preview} sandbox="allow-scripts"/>}<div className="lab-actions"><button className="btn btn-secondary" onClick={checkLab}>Check my work</button>{labMsg&&<span>{labMsg}</span>}</div></div>}<button className="btn btn-primary" onClick={complete}>{nextHref?'Complete & continue':'Complete lesson'}</button></div>}
 {tab==='transcript'&&<div className="reading-card"><h2>Lesson transcript</h2><LessonNotes text={lesson.transcript}/></div>}
 {tab==='tutor'&&<div className="tutor-card"><h2>Ask your AI tutor</h2><p>Ask about this lesson, request another example, or ask for a hint without revealing the answer.</p><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would you like help with?"/><button onClick={ask} className="btn btn-primary" disabled={asking}>{asking?'Thinking…':'Ask tutor'}</button>{answer&&<div className="tutor-answer">{answer}</div>}</div>}
 </div>}
