import type { Course, Module, Lesson } from "./types";

const image=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;

export const starterCourses: Course[] = [
  {id:"course-web",slug:"full-stack-web-development",title:"Full-Stack Web Development",subtitle:"Build modern websites and production-ready web applications from the ground up.",description:"Learn HTML, CSS, JavaScript, React, APIs, databases, authentication, Git and deployment through AI-guided lessons and practical labs.",category:"Software Development",level:"Beginner to Intermediate",price:120,currency:"USD",duration:"12 weeks",image:image("photo-1498050108023-c5249f4df085"),featured:true,published:true,outcomes:["Build responsive websites","Create interactive JavaScript applications","Build React interfaces","Design APIs and database-backed applications","Deploy production projects"],requirements:["A computer","Internet connection","No prior programming experience required"]},
  {id:"course-python",slug:"python-programming",title:"Python Programming",subtitle:"Learn programming fundamentals and build useful Python projects.",description:"A practical introduction to Python covering variables, logic, functions, files, APIs and project development.",category:"Programming",level:"Beginner",price:60,currency:"USD",duration:"6 weeks",image:image("photo-1526379879527-8559ecfcaec0"),featured:true,published:true,outcomes:["Write clean Python programs","Use functions and data structures","Work with files and APIs","Build portfolio projects"],requirements:["A computer","No previous coding experience required"]},
  {id:"course-git",slug:"git-and-github",title:"Git & GitHub",subtitle:"Manage code professionally and collaborate with confidence.",description:"Learn repositories, commits, branches, pull requests, collaboration and practical Git workflows.",category:"Developer Tools",level:"Beginner",price:25,currency:"USD",duration:"2 weeks",image:image("photo-1618401471353-b98afee0b2eb"),featured:false,published:true,outcomes:["Use Git confidently","Publish repositories to GitHub","Work with branches","Collaborate through pull requests"],requirements:["A computer","Basic computer skills"]},
  {id:"course-cloud",slug:"cloud-and-devops-foundations",title:"Cloud & DevOps Foundations",subtitle:"Understand cloud infrastructure, Linux, containers and modern deployment workflows.",description:"A practical foundation for learners moving toward cloud engineering and DevOps careers.",category:"Cloud & DevOps",level:"Intermediate",price:150,currency:"USD",duration:"10 weeks",image:image("photo-1451187580459-43490279c0fa"),featured:true,published:true,outcomes:["Understand cloud architecture","Use Linux command line","Work with containers","Understand CI/CD","Deploy applications"],requirements:["Basic programming knowledge recommended"]},
  {id:"course-cyber",slug:"cybersecurity-foundations",title:"Cybersecurity Foundations",subtitle:"Build strong foundations in digital security, networks and defensive thinking.",description:"Learn core security concepts, safe systems practices, networks, authentication and introductory defensive labs.",category:"Cybersecurity",level:"Beginner",price:75,currency:"USD",duration:"6 weeks",image:image("photo-1563013544-824ae1b704d3"),featured:false,published:true,outcomes:["Understand common cyber risks","Apply secure account practices","Understand network security basics","Perform safe defensive exercises"],requirements:["A computer","Basic computer skills"]},
  {id:"course-ai",slug:"ai-productivity",title:"AI for Productivity",subtitle:"Use modern AI tools responsibly for study, work and entrepreneurship.",description:"Learn prompting, research workflows, content development, analysis and practical automation with AI.",category:"Artificial Intelligence",level:"Beginner",price:35,currency:"USD",duration:"3 weeks",image:image("photo-1677442136019-21780ecad995"),featured:false,published:true,outcomes:["Write effective prompts","Research with AI responsibly","Build repeatable AI workflows","Automate routine knowledge work"],requirements:["Internet connection","Basic digital literacy"]}
];

export const starterModules: Module[] = starterCourses.map((c,i)=>({id:`module-${i+1}`,courseId:c.id,title:"Core Skills",position:1}));

const theory=(courseId:string,moduleId:string,id:string,slug:string,title:string,summary:string,content:string):Lesson=>({id,moduleId,courseId,slug,title,type:"theory",position:1,durationMinutes:25,summary,content,transcript:`In this lesson, your AI instructor introduces ${title}. We connect the concept to practical work, review the essential vocabulary, and finish with a clear example you can revisit at any time.`});
const lab=(courseId:string,moduleId:string,id:string,slug:string,title:string,language:"html"|"javascript"|"python"|"shell"|"text",starterCode:string,instructions:string[],expectedContains:string[]):Lesson=>({id,moduleId,courseId,slug,title,type:"practical",position:2,durationMinutes:40,summary:"Practice the core skill in a guided interactive lab.",content:"Follow each instruction, edit the workspace, check your work, and ask the AI tutor for a hint whenever you need one.",transcript:`This practical lesson guides you through ${title}. Work step by step and focus on understanding why each action matters.`,lab:{language,starterCode,instructions,expectedContains}});

export const starterLessons: Lesson[] = [
 theory("course-web","module-1","web-1","web-foundations","How the Web Works","Understand browsers, servers, URLs and HTTP.","A browser requests resources from a server using URLs and HTTP. Modern web applications combine HTML for structure, CSS for presentation, JavaScript for interaction, and APIs for data."),
 lab("course-web","module-1","web-2","first-web-page","Build Your First Web Page","html","<!doctype html>\n<html>\n<body>\n\n</body>\n</html>",["Add a header with an h1.","Add a main section with a paragraph.","Add a link labelled Start learning."],["<header","<h1","<main","Start learning"]),
 theory("course-python","module-2","py-1","python-foundations","Python Foundations","Understand values, variables and program flow.","Python is a readable general-purpose language. Programs combine values, variables, expressions, conditions, loops and functions to solve problems."),
 lab("course-python","module-2","py-2","python-basics","Write a Python Program","python","name = 'Sawa learner'\n",["Print the name variable.","Create an age variable.","Print a sentence using both variables."],["print(","age"]),
 theory("course-git","module-3","git-1","git-workflow","Repositories & Commits","Understand version control and meaningful snapshots.","Git records project history as commits. A good workflow inspects changes, stages intentional files and creates clear commits."),
 lab("course-git","module-3","git-2","git-practice","Practice the Git Workflow","shell","# Enter the commands below\n",["Initialize a repository.","Check status.","Stage all files.","Create a commit."],["git init","git status","git add","git commit"]),
 theory("course-cloud","module-4","cloud-1","cloud-model","How Cloud Computing Works","Understand compute, storage, networking and managed services.","Cloud platforms provide programmable infrastructure organized into regions, services and availability zones. Strong foundations come before provider-specific dashboards."),
 lab("course-cloud","module-4","cloud-2","linux-basics","Linux Command Line","shell","# Practice commands here\n",["Print the current directory.","List files.","Create a directory named sawa-lab.","Create a file inside it."],["pwd","ls","mkdir","touch"]),
 theory("course-cyber","module-5","cyber-1","security-thinking","Security Thinking","Learn assets, threats, vulnerabilities and risk.","Security begins with understanding what you protect, what can go wrong, and which controls reduce risk. Defensive thinking prioritizes prevention, detection and recovery."),
 lab("course-cyber","module-5","cyber-2","account-security","Account & Device Security","text","Account audit:\n- Password: reused\n- MFA: off\n- Recovery email: old address\n",["Identify the highest-risk issue.","Recommend a unique-password strategy.","Recommend MFA.","Explain how to fix account recovery."],["password","MFA"]),
 theory("course-ai","module-6","ai-1","ai-responsibility","Using AI Well","Understand context, verification and responsible use.","AI can accelerate work, but useful results depend on clear goals, relevant context, appropriate constraints and verification of important claims."),
 lab("course-ai","module-6","ai-2","prompting","Prompting Foundations","text","Write a social media post about my event.",["Add the audience.","Add the event purpose.","Specify the tone.","Specify a maximum length."],["audience","tone"])
];